export const CONNECT_WALLET = 'CONNECT_WALLET';
export const CONNECT_GUEST = 'CONNECT_GUEST';
export const DISCONNECT_WALLET = 'DISCONNECT_WALLET';
export const LOAD_CONTRACT = 'LOAD_CONTRACT';
export const CREATE_NFT = 'CREATE_NFT';
export const FETCH_ALL_NFTS = 'FETCH_ALL_NFTS';
export const FETCH_SINGLE_NFT = 'FETCH_SINGLE_NFT';
export const ERROR = 'ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const MONITOR_ACCOUNT_CHANGED = 'MONITOR_ACCOUNT_CHANGED';
export const MONITOR_DISCONNECT = 'MONITOR_DISCONNECT';

//Ardor
export const FETCH_ARDOR_NFTS = 'FETCH_ARDOR_NFTS';
export const MINT_ARDOR_NFT = 'MINT_ARDOR_NFT';
export const GENERATE_AUTH = 'GENERATE_AUTH';
export const WATCH_TOKEN = 'WATCH_TOKEN';
export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const DISCONNECT_ARDOR_WALLET = 'DISCONNECT_ARDOR_WALLET';