export const CONNECT_WALLET = 'CONNECT_WALLET';
export const CONNECT_GUEST = 'CONNECT_GUEST';
export const DISCONNECT_WALLET = 'DISCONNECT_WALLET';
export const LOAD_CONTRACT = 'LOAD_CONTRACT';
export const CREATE_NFT = 'CREATE_NFT';
export const FETCH_ALL_NFTS = 'FETCH_ALL_NFTS';
export const FETCH_AUCTIONED_NFTS = 'FETCH_AUCTIONED_NFTS';
export const FETCH_SINGLE_NFT = 'FETCH_SINGLE_NFT';
export const PLACE_ETHEREUM_BID = 'PLACE_ETHEREUM_BID';
export const SELL_ETHEREUM_NFT = 'SELL_ETHEREUM_NFT';
export const FETCH_ETHEREUM_PERSONAL_ASSETS = 'FETCH_ETHEREUM_PERSONAL_ASSETS';
export const MONITOR_ACCOUNT_CHANGED = 'MONITOR_ACCOUNT_CHANGED';
export const MONITOR_DISCONNECT = 'MONITOR_DISCONNECT';

//Ardor
export const FETCH_ARDOR_NFTS = 'FETCH_ARDOR_NFTS';
export const FETCH_SINGLE_ARDOR_NFT = 'FETCH_SINGLE_ARDOR_NFT';
export const MINT_ARDOR_NFT = 'MINT_ARDOR_NFT';
export const GENERATE_AUTH = 'GENERATE_AUTH';
export const WATCH_TOKEN = 'WATCH_TOKEN';
export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const DISCONNECT_ARDOR_WALLET = 'DISCONNECT_ARDOR_WALLET';
export const FETCH_ARDOR_BIDS = 'FETCH_ARDOR_BIDS';
export const PLACE_ARDOR_BID = 'PLACE_ARDOR_BID';
export const FETCH_ARDOR_PERSONAL_ASSETS = 'FETCH_ARDOR_PERSONAL_ASSETS';

//Reset NFT Detail Page
export const RESET_NFT_ITEM = 'RESET_NFT_ITEM';

//Authentication
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//For Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';